app/urls.py
from django.conf.urls import url, patterns, include

from project import settings
from app import views

urlpatterns = patterns('',
                       url(r'^$', views.feed, name='index'),
                       url(r'^register/$', views.register, name='register'),
                       url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
                       url(r'^login/$', views.login, name='login'),
                       url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/login'}),
                       url(r'^profile/',
                           include(patterns('',
                                            url(r'^(?P<pk>[0-9]+)/$', views.profile, name='profile'),
                                            url(r'^$', views.profile, name='my_profile'),
                                            ))),

                       url(r'^followers/',
                           include(patterns('',
                                            url(r'^(?P<pk>[0-9]+)/$', views.followers, name='followers'),
                                            url(r'^$', views.followers, name='my_followers'),
                                            ))),
                       url(r'^following/',
                           include(patterns('',
                                            url(r'^(?P<pk>[0-9]+)/$', views.following, name='following'),
                                            url(r'^$', views.following, name='following_me'),
                                            ))),

                       url(r'^post/(?P<pk>[0-9]+)/$', views.post, name='post'),

                       url(r'^settings/$', views.settings, name='settings'),
                       url(r'^feed/$', views.feed, name='feed'),

                       url(r'^manage_comment/$', views.manage_comment, name='manage_comment'),

                       url(r'^manage_post/$', views.manage_post, name='manage_post'),

                       url(r'^follow/$', views.follow, name='follow'),
                       url(r'^unfollow/$', views.unfollow, name='unfollow'),

                       url(r'^api/check_email/$', views.check_email, name='check_email'),
                       )

if settings.DEBUG:
    urlpatterns += patterns('', url(r'media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }))

project/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic import RedirectView

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'app.views.home', name='home'),
    # url(r'^app/', include('app.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('app.urls')),
)

app/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from app import config


def content_file_name(instance, filename):
    return 'avatars/' + str(instance.user.pk)


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    username = models.TextField(max_length=256)
    fullname = models.TextField(max_length=256, blank=True)
    about = models.TextField(max_length=1024, blank=True)
    avatar = models.ImageField("Avatar", upload_to=content_file_name, blank=True, null=True)

    following = models.ManyToManyField('self', blank=True, symmetrical=False, related_name='followers')

    hour_start = models.IntegerField(default=config.DEFAULT_TIME_START,
                                     validators=[MaxValueValidator(23), MinValueValidator(0)])
    hour_span = models.IntegerField(default=config.DEFAULT_TIME_SPAN,
                                    validators=[MinValueValidator(1), MaxValueValidator(config.MAX_TIME_SPAN)])

    def __unicode__(self):
        return self.user.username


User.profile = property(lambda u: UserProfile.objects.get_or_create(user=u)[0])


class Post(models.Model):
    user = models.ForeignKey(User)
    title = models.TextField()
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post)

templates/jay/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block title %}{% endblock %} — Jay</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/parsley.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% block styles %}{% endblock %}
<body>

<!-- Begin Navbar -->
{% include 'jay/navbar.html' %}
<!-- /.navbar -->

    <div class="container">
    <div class="row">
       <div class="col-sm-9 well">
            {% block body_block %}{% endblock %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-sm-3">
            {% block sidebar %}{% endblock %}
        </div>
    </div>
</div>

<script src="{% static 'js/jquery-2.1.1.js' %}"></script>
<script src="{% static 'js/ajax_functions.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/date.format.js' %}" ></script>
{% block scripts %}{% endblock %}
{% block body_bottom %}{% endblock %}
</body>
</html>

templates/jay/chat.html
{% extends 'jay/base.html' %}
{% block title %}Chat{% endblock %}

{% block extrahead %}
    <script type="text/javascript">
        $(document).ready(function(){
            activate_chat({{ thread_id }}, "{{ user.username }}", {
                "total": {{ messages_total }},
                "sent": {{ messages_sent }},
                "received": {{ messages_received }}
            });
        });
    </script>
{% endblock %}

{% block body_block %}
    <div class="chat">
    <div class="partner">
        <p class="name">{{ partner.username }}</p>
        <p class="messages"><span class="total">{{ messages_total }}</span> messages (<span class="received">{{ messages_received }}</span> received, <span class="sent">{{ messages_sent }}</span> sent)</p>
    </div>
    <div class="conversation">
        {% for message in thread_messages reversed %}
        <div class="message">
            {% if message.sender == user %}<p class="author we"><span class="datetime">{{ message.datetime|date:"d.m.Y H:i:s" }}</span> {{ user.username }}:</p>{% else %}<p class="author partner"><span class="datetime">{{ message.datetime|date:"d.m.Y H:i:s" }}</span> {{ partner.username }}:</p>{% endif %}
            <p class="message">{{ message.text|linebreaksbr }}</p>
        </div>
        {% endfor %}
    </div>
    <form class="message_form">
        <div class="compose">
            <textarea rows="1" cols="30" id="message_textarea"></textarea>
        </div>
        <div class="send">
            <button class="btn" type="button">Send</button>

        </div>
    </form>
</div>
{% endblock %}

templates/jay/edit_profile.html
{% extends 'jay/base.html' %}
{% block title %}Edit profile{% endblock %}
{% load static %}

{% block body_block %}
    <form class="form-horizontal" action="." method="post" enctype="multipart/form-data" data-parsley-validate>
        {% csrf_token %}
        <div class="form-group">
            <label for="inputUsername" class="col-sm-2 control-label required">Username</label>

            <div class="col-sm-10">
                <input type="text" name="username" class="form-control" id="inputUsername" data-parsley-required
                       data-parsley-length="[3, 20]" value="{{ user.profile.username }}">
            </div>
        </div>
        <div class="form-group">
            <label for="inputFullname" class="col-sm-2 control-label">Full name</label>

            <div class="col-sm-10">
                <input type="text" name="fullname" class="form-control" id="inputFullname"
                       value="{{ user.profile.fullname }}">
            </div>
        </div>
        <div class="form-group">
            <label for="inputAbout" class="col-sm-2 control-label">Bio</label>

            <div class="col-sm-10">
                <textarea name="about" class="form-control" id="inputAbout" rows="6">{{ user.profile.about }}</textarea>
            </div>
        </div>
        <div class="form-group">
            <label for="inputAvatar" class="col-sm-2 control-label">Avatar</label>

            <div class="col-sm-8">
                <div class="input-group">
                <span class="input-group-btn">
                    <span class="btn btn-info btn-file">
                        Browse <input type="file" name="avatar">
                    </span>
                </span>
                    <input type="text" id="inputAvatar" class="form-control" readonly>
                </div>
            </div>
            <div class="col-sm-2">
                <img src="/media/avatars/{{ user.pk }}_small.png" class="img-responsive"/>
            </div>
        </div>

        <div class="form-group">
            <label for="timeSpan" class="col-sm-2 control-label">Posting time</label>

            <div class="col-sm-10">
                From
                <button id="time-start" class="btn btn-default" data-jq-dropdown="#time-start-dropdown">
                    {% if user.profile.hour_start < 10 %}0{% endif %}{{ user.profile.hour_start }}:00
                </button>
                during
                <button id="time-span" class="btn btn-default"
                        data-jq-dropdown="#time-span-dropdown">{{ user.profile.hour_span }} hours
                </button>
            </div>
            <input type="hidden" id="timeStart" name="timeStart" value="{{ user.profile.hour_start }}"/>
            <input type="hidden" id="timeSpan" name="timeSpan" value="{{ user.profile.hour_span }}"/>
        </div>
        {% if changed %} <p>Changes saved.</p> {% endif %}
        <div class="col-md-offset-2">
            <button class="btn btn-primary">Save</button>
        </div>
    </form>


{% endblock %}

{% block scripts %}

    <script>
        $(document).on('change', '.btn-file :file', function () {
            var input = $(this),
                    numFiles = input.get(0).files ? input.get(0).files.length : 1,
                    label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
            input.trigger('fileselect', [numFiles, label]);
        });

        function setupDropdowns() {
            var startDropdown = $('#time-start-dropdown').find('.jq-dropdown-menu');
            for (var i = 1; i <= 23; i++) {
                var time = (i < 10 ? "0" + i : "" + i) + ":00";
                startDropdown.append("<li><a href='#' data-value='" + i + "'>" + time + "</a></li>");
            }
            var spanDropdown = $('#time-span-dropdown').find('.jq-dropdown-menu');
            for (var j = 1; j <= 6; j++) {
                spanDropdown.append("<li><a href='#' data-value='" + j + "'>" + j + " hours</a></li>");
            }

            var timeStartButton = $('#time-start');
            var timeSpanButton = $('#time-span');
            var hiddenTimeStart = $('#timeStart');
            var hiddenTimeSpan = $('#timeSpan');
            startDropdown.find('li > a').click(function () {
                timeStartButton.text($(this).text());
                hiddenTimeStart.val($(this).attr("data-value"));
            });
            spanDropdown.find('li > a').click(function () {
                timeSpanButton.text($(this).text());
                hiddenTimeSpan.val($(this).attr("data-value"));
            });
        }
        $(document).ready(function () {
            $('.btn-file :file').on('fileselect', function (event, numFiles, label) {

                var input = $(this).parents('.input-group').find(':text'),
                        log = numFiles > 1 ? numFiles + ' files selected' : label;

                if (input.length) {
                    input.val(log);
                } else {
                    if (log) alert(log);
                }

            });

            setupDropdowns();
        });
    </script>

    <script src="{% static 'js/parsley.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.dropdown.js' %}"></script>
{% endblock %}

{% block styles %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/jquery.dropdown.min.css' %}"/>
{% endblock %}

{% block sidebar %}
    {% include 'jay/sidebar.html' %}
{% endblock %}

{% block body_bottom %}
    <div id="time-start-dropdown" class="jq-dropdown jq-dropdown-scroll">
        <ul class="jq-dropdown-menu">
        </ul>
    </div>
    <div id="time-span-dropdown" class="jq-dropdown">
        <ul class="jq-dropdown-menu">
        </ul>
    </div>
{% endblock %}

templates/jay/feed.html
{% extends 'jay/base.html' %}

{% block title %}Feed{% endblock %}

{% block body_block %}
    {% include 'jay/post_list.html' %}
{% endblock %}

{% block sidebar %}
    {% include 'jay/sidebar.html' %}
{% endblock %}

templates/jay/following.html
{% extends 'jay/base.html' %}
{% block title %}Following{% endblock %}
{% block body_block %}

    {% if user_data == user %}You are {% else %}{{ user_data.profile.username }} is {% endif %}following {{ following.count }} people.

    {% if following %}
        {% with users=following %}
            {% include "jay/user_list.html" %}
        {% endwith %}
    {% endif %}
{% endblock %}

{% block sidebar %}
    {% include 'jay/sidebar.html' %}
{% endblock %}

templates/jay/friends.html
{% extends 'jay/base.html' %}
{% block body_block %}
    <h3>{{ user_data.first_name }}'s Friends</h3>

    <ul class="nav nav-tabs">
        <li class="active"><a href="#friends" data-toggle="tab">Friends</a></li>
        <li><a href="#requests" data-toggle="tab">Requests {% if requests %}({{ requests.count  }}){% endif %}</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active" id="friends">
            {% for friend in friends %}
                {% for friend in friends %}
                    <a href="/profile/{{ friend.user.pk }}">
                        <img src="/media/avatars/{{ friend.user.pk }}_small.png"/>
                        {{ friend.user.first_name }} {{ friend.user.last_name }}
                    </a>
                {% endfor %}
            {% endfor %}
        </div>
        <div class="tab-pane" id="requests">
            {% for request in requests %}
                {{ request.user.first_name }} {{ request.user.last_name }}
                <button id="add_friend" data-username="{{ request.user.username }}"
                                            class="btn btn-mini btn-primary" type="button">Add friend
                                    </button>
                                    <button id="decline_request" data-username="{{ request.user.username }}"
                                            class="btn btn-mini btn-secondary" type="button">Decline request
                                    </button>
            {% endfor %}
        </div>

    </div>

{% endblock %}

templates/jay/index.html
{% extends 'jay/base.html' %}
{% block title %}  — Index {% endblock %}

templates/jay/manage_post.html
{% extends 'jay/base.html' %}
{% load static %}
{% block title %}New story{% endblock %}
{% block body_block %}
    <h3 class="col-sm-offset-2">What happened today?</h3>
    <form class="form-horizontal" action="." method="post" enctype="multipart/form-data" data-parsley-validate>
        {% csrf_token %}
        <div class="form-group">
            <label for="inputContent" class="col-sm-2 control-label required">Story</label>

            <div class="col-sm-10">
                <textarea name="content" class="form-control" id="inputContent" rows="8" data-parsley-required>{{ post.content }}</textarea>
            </div>
        </div>

        <input type="hidden" name="pk" value="{{ post.pk }}">

        <div class="col-md-offset-2">
            <button class="btn btn-primary" type="submit">Save</button>
            {% if post %}<button class="btn btn-danger" type="button" id="delete_post" data-post_pk="{{ post.pk }}">Delete</button>{% endif %}
        </div>
    </form>
{% endblock %}

{% block sidebar %}
   {% include 'jay/sidebar.html' %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/parsley.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'select2/select2.js' %}"></script>

{% endblock %}

{% block styles %}
    <link href="{% static 'css/datepicker.css' %}" rel="stylesheet">
    <link href="{% static 'select2/select2-bootstrap.css' %}" rel="stylesheet">
{% endblock %}

templates/jay/navbar.html
<div class="navbar navbar-static">
    <div class="container">
        <a class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
            <span class="glyphicon glyphicon-chevron-down"></span>
        </a>

        {% with auth=user.is_authenticated %}
            <div class="nav-collapse collase">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="/">Jay</a></li>
                    {% if auth %}
                        <li><a href="/profile/">Profile</a></li>
                        <li><a href="/feed/">Feed</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if auth %}
                        <li><img src="/media/avatars/{{ user.pk }}_small.png" class="img-responsive navbar-avatar"/>
                        </li>
                        <li><a href="/logout/">Log out</a></li>
                    {% else %}
                        <li><a href="/register/">Register</a></li>
                        <li><a href="/login/">Sign in</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endwith %}
    </div>
</div>

templates/jay/post.html
{% extends 'jay/base.html' %}
{% block body_block %}
    <a href="/profile/{{ post.user.pk }}"><strong>{{ post.user.profile.username }}</strong></a>
    posted {{ post.timestamp }}
    <article>
        {{ post.content }}
    </article>
    <div class="comments well-sm">
        Comments:<br/>

        <div class="comments_list" id="comments_{{ post.pk }}">
            {% if post.comment_set %}
                {% for comment in post.comment_set.all %}

                    <div class="comment row" id="comment_{{ comment.pk }}">
                        <div class="col-sm-2">
                            <a href="/profile/{{ comment.user.pk }}/" class="user_name">
                                <img src="/media/avatars/{{ comment.user.pk }}_small.png"/>
                                {{ comment.user.first_name }} {{ comment.user.last_name }}</a>
                        </div>

                        <div class="col-sm-10">
                            <div class="comment_text">{{ comment.text }}</div>
                            <p class="timestamp">{{ comment.timestamp }}</p>
                        </div>
                    </div>

                    {% if comment.user == user %}
                        <textarea cols="40" class="edit_comment_field input-group" name="text"
                                  id="styled" rows="1" style="display:none"></textarea>
                        <button data-comment_id="{{ comment.pk }}"
                                class="edit_comment btn btn-default btn-xs" type="button">edit
                        </button>
                        <button data-comment_id="{{ comment.pk }}"
                                class="delete_comment btn btn-default btn-xs" type="button">x
                        </button><br/>
                    {% endif %}
                    </div>
                {% endfor %}
            {% endif %}
    </div>
    <div class="input-group">
        <input type="text" class="form-control comment_text">
                            <span class="input-group-btn">
                                <button class="btn btn-default add_comment" type="button" data-post_id="{{ post.pk }}">
                                    Comment
                                </button>
                            </span>
        <!-- /input-group -->


    </div>
    </div>

{% endblock %}

templates/jay/profile.html
{% extends 'jay/base.html' %}
{% block title %} {{ user_data.profile.username }}{% endblock %}

{% block body_block %}
    <h3>Posts</h3>
    {% if posts %}
        {% include 'jay/post_list.html' %}
    {% endif %}


{% endblock %}

{% block sidebar %}
    {% include 'jay/sidebar.html' %}
{% endblock %}

templates/jay/settings.html
{% extends 'jay/base.html' %}
{% block title %}Settings{% endblock %}
{% block head %}
     <form action="." method="post">
    {% csrf_token %}
    {{ change_password_form.errors }}
    {{ change_password_form.as_p }}
    {% if changed %} <p>Changes saved.</p> {% endif %}
    <div class="submit-wrapper">
        <input type="submit" value="Save"/>
    </div>
    </form>
{% endblock %}

templates/jay/sidebar.html
<button class="btn btn-primary btn-block" style="margin-bottom: 10px;"
        onclick="window.location='/manage_post/?action=add'"><strong>Today I...</strong></button>
<div class="well">
    {% with userdata=user_data|default:user %}
        <img src="/media/avatars/{{ userdata.pk }}_med.png" class="img-responsive center-block"/>

        <p class="text-center">
            <span class="username">{{ userdata.profile.username }}</span>
            <br>{{ userdata.profile.fullname }}
        </p>


        <div class="btn-group-vertical btn-block" id="user_menu">
            {% if userdata == user %}
                <button type="button" class="btn btn-link" onclick="window.location='/edit_profile'">Edit profile
                </button>

            {% elif is_following %}
                <button type="button" class="btn btn-default" id="unfollow_btn" data-user-pk="{{ userdata.pk }}">
                    Unfollow
                </button>
            {% else %}
                <button type="button" class="btn btn-primary" id="follow_btn" data-user-pk="{{ userdata.pk }}">Follow
                </button>
            {% endif %}
            <button type="button" class="btn btn-default">{{ userdata.post_set.count }} posts</button>
            <button type="button" class="btn btn-default" id="following_btn"
                    onclick="window.location='/following/{{ userdata.pk }}'">{{ userdata.profile.following.count }} following
            </button>
            <button type="button" class="btn btn-default" id="followers_btn"
                    onclick="window.location='/followers/{{ userdata.pk }}'">{{ userdata.profile.followers.count }} followers
            </button>
        </div>
    {% endwith %}
</div>

templates/jay/user_list.html
<div class="list-group">

    {% for profile in users %}
        <a href="/profile/{{ profile.user.pk }}">
            <div class="list-group-item user-item">
                <div class="row">
                    <div class="col-sm-2">
                        <div class="row">
                            <img src="/media/avatars/{{ profile.user.pk }}_small.png"
                                 class="img-responsive center-block"/>
                        </div>
                        <div class="row username text-center">
                            {{ profile.username }}
                        </div>
                    </div>
                    <div class="col-sm-10">
                        Last story:
                    </div>
                </div>
            </div>
        </a>
    {% endfor %}

</div>